name: Unit tests

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  run:
    name: Unit Tests (${{ matrix.oses }})
    runs-on: farm
    strategy:
      matrix:
        oses: [UBUNTU, WIN]
    env:
      VM_IMAGE: ${{ matrix.oses }}

    steps:
      - name: Show ip
        if: ${{ matrix.oses == 'UBUNTU' }}
        run: ip addr show
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: npm install
        run: npm install
      - name: Run Tests
        run: npm run test
